{% set name = "progress" %}
{% set version = "1.5" %}
{% set hash_type = "sha256" %}
{% set hash_val = "69ecedd1d1bbe71bf6313d88d1e6c4d2957b7f1d4f71312c211257f7dae64372" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - progress

about:
  home: https://github.com/verigak/progress
  license: ISC
  license_family: MIT
  license_file: LICENSE
  summary: 'Easy progress reporting for Python'
  doc_url: https://pypi.python.org/pypi/progress
  dev_url: https://github.com/verigak/progress

extra:
  recipe-maintainers:
    - SoapZA
