appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UJzPonNKH1i6m+dLGoCK7yD7gz3KgEodA4ua6oYjo6hO5lRlj76Lbu1OfS/LDZ7SfANjp/wQrJxCrvMWa4snF57RcPNhcXlVjGQzyEp2MWhRLk8PFd0kGiIPUoR3+aGJ+2mqeufD3w5c3eVIw0OMdBN8RLH0kqIo7+sMvn6qbrA6ycvITZzx/kdmWhCtiK+ZFLMjNYN+NB59rBv6hpLg7Ugc2sKEI2P9hNPpLVi8/t+hjOVzXwYKv7P9rHiJEwUflt4g9pEGHIlrRMl3MbpT8MXBl6jlt3AE8I3Vgz5h7D/DqQROa6KdL+glWElQelrmkvIInLcyR7+CNgXRjFmLIKhK4iMwCdohX5xw7VPp3/mDugVhjD/ktnpZ8sKmw/Vt2HfE/zsqXgioQPI5+/1PEMDdvZ8C9kvvPlxoO4sbMuFiOSWMJxqYhHRatAf9DFeahmi8QG6EmmQfEP29G+RRvM0fNmwIBWBKqmEEf4SLpNhx5+b4HwYzdEJ7tmsyRqBaAGVc3y1Z/vh5E47coXbLUqsV98elt5KUpFOfLGYUoyq5xwKGRzkMOlmSydqjZt2GCCjkub5Egn/C5xEKSbghSSKrzfiAQiMHSUPGlZUtedTl6mMpSNoWYWOBDvLDONjW1BzwRaRc8z6iqAQq/i8RAY0tMzs8q58dSr6Kr5ABHG4=}
